In [76]:
import pandas as pd

In [77]:
list_df = pd.read_html('https://en.wikipedia.org/wiki/List_of_lakes_by_area', match = 'Water volume', header=0)

In [78]:
lakes = list_df[0]

In [79]:
lakes

,Unnamed: 0,Name,Countries with shoreline,Area,Length,Maximum depth,Water volume,Thumbnail (same scale for all lakes),Notes
0,NaN,Caspian Sea*,Kazakhstan Russia Turkmenistan Azerbaijan Iran,"2 (143,000 sq mi)",NaN,NaN,"3 (18,800 cu mi)",NaN,"Despite its name, the Caspian Sea is often reg..."
1,NaN,Superior[n 1],Canada United States,"2 (31,700 sq mi)[14]",[14],[14],"3 (2,900 cu mi)[14]",NaN,"Largest of the Great Lakes by volume, having m..."
2,NaN,Victoria,Uganda Kenya Tanzania,"2 (26,590 sq mi)",NaN,NaN,3 (660 cu mi),NaN,The largest lake by area in Africa.[17]
3,NaN,Huron[n 1],Canada United States,"2 (23,000 sq mi)[14]",[14],[14],3 (850 cu mi)[14],NaN,"Contains Manitoulin Island, the world's larges..."
4,NaN,Michigan[n 1],United States,"2 (22,000 sq mi)[14]",[14],[14],"3 (1,200 cu mi)[14]",NaN,Largest lake contained within one country.
5,NaN,Tanganyika,Burundi Tanzania Zambia Democratic Republic of...,"2 (12,600 sq mi)",NaN,NaN,"3 (4,500 cu mi)",NaN,Longest freshwater lake in the world and secon...
6,NaN,Baikal,Russia,"2 (12,200 sq mi)",NaN,NaN,"3 (5,700 cu mi)",NaN,Deepest lake in the world and largest volume f...
7,NaN,Great Bear Lake,Canada,"2 (12,000 sq mi)",NaN,NaN,3 (536 cu mi),NaN,Largest lake entirely within Canada[21]
8,NaN,Malawi,Malawi Mozambique Tanzania,"2 (11,400 sq mi)",NaN,NaN,"3 (2,000 cu mi)",NaN,NaN
9,NaN,Great Slave Lake,Canada,"2 (10,000 sq mi)",NaN,NaN,3 (370 cu mi),NaN,Deepest lake in North America[22]
10,NaN,Erie,Canada United States,"2 (9,900 sq mi)[14]",[14],[14],3 (117 cu mi)[14],NaN,NaN
11,NaN,Winnipeg,Canada,"2 (9,465 sq mi)",NaN,NaN,3 (68 cu mi),NaN,NaN
12,NaN,Ontario,Canada United States,"2 (7,320 sq mi)[14]",[14],[14],3 (393 cu mi)[14],NaN,NaN
13,NaN,Ladoga,Russia,"2 (7,000 sq mi)",NaN,NaN,3 (218 cu mi),NaN,Largest lake in Europe[23]
14,NaN,Balkhash*,Kazakhstan,"2 (6,300 sq mi)",NaN,NaN,3 (25 cu mi),NaN,NaN
15,NaN,Vostok,Antarctica,"2 (4,800 sq mi)",NaN,NaN,"3 (1,300 ± 380 cu mi)",NaN,Largest lake in Antarctica
16,NaN,Onega,Russia,"2 (3,700 sq mi)",NaN,NaN,3 (68 cu mi),NaN,NaN
17,NaN,Titicaca,Bolivia Peru,"2 (3,232 sq mi)",NaN,NaN,3 (214 cu mi),NaN,Largest lake in South America. Has a smaller s...
18,NaN,Nicaragua,Nicaragua,"2 (3,191 sq mi)",NaN,NaN,3 (26 cu mi),NaN,Largest lake in Central America
19,NaN,Athabasca,Canada,"2 (3,030 sq mi)",NaN,NaN,3 (49 cu mi),NaN,NaN
20,NaN,Taymyr,Russia,"2 (2,700 sq mi)",NaN,NaN,3 (3.1 cu mi),NaN,Largest lake entirely north of the Arctic Circ...
21,NaN,Turkana*,Ethiopia Kenya,"2 (2,473 sq mi)",NaN,NaN,3 (49 cu mi),NaN,Largest permanent desert lake and the world's ...
22,NaN,Reindeer Lake,Canada,"2 (2,440 sq mi)",NaN,NaN,3 (22.85 cu mi),NaN,NaN
23,NaN,Issyk-Kul*,Kyrgyzstan,"2 (2,400 sq mi)",NaN,NaN,3 (417 cu mi),NaN,NaN
24,NaN,Urmia*,Iran,"2 (2,317 sq mi)",NaN,NaN,NaN,NaN,NaN
25,NaN,Vänern,Sweden,"2 (2,141 sq mi)",NaN,NaN,3 (37 cu mi),NaN,Largest lake in the European Union
26,NaN,Winnipegosis,Canada,"2 (2,086 sq mi)",NaN,NaN,NaN,NaN,NaN
27,NaN,Albert,Uganda Democratic Republic of the Congo,"2 (2,046 sq mi)",NaN,NaN,3 (67 cu mi),NaN,NaN
28,NaN,Mweru,Zambia Democratic Republic of the Congo,"2 (1,980 sq mi)",NaN,NaN,3 (9.1 cu mi),NaN,NaN
29,NaN,Nettilling,Canada,"2 (1,956 sq mi)",NaN,NaN,NaN,NaN,Lake is on Baffin Island and is the largest la...
...,...,...,...,...,...,...,...,...,...
32,NaN,Great Salt Lake*,United States,"2 (1,800 sq mi)",NaN,NaN,3 (4.54 cu mi),NaN,Largest saltwater lake in the Western Hemisphe...
33,NaN,Qinghai Lake*,China,"2 (1,733 sq mi) (2007)",NaN,NaN,NaN,NaN,NaN
34,NaN,Saimaa,Finland,"≈ 4,400 km2 (1,700 sq mi)",NaN,NaN,3 (8.6 cu mi),NaN,NaN
35,NaN,Lake of the Woods,Canada United States,"4,350 km2 (1,680 sq mi)",NaN,NaN,3 (4.7 cu mi),NaN,"Most islands of any lake, with around 14,632 i..."
36,NaN,Khanka,China Russia,"4,190 km2 (1,620 sq mi)",NaN,NaN,3 (4.4 cu mi),NaN,NaN
37,NaN,Sarygamysh,Uzbekistan Turkmenistan,"3,955 km2 (1,527 sq mi)",NaN,NaN,3 (16.45 cu mi),NaN,NaN
38,NaN,Dubawnt,Canada,"3,833 km2 (1,480 sq mi)",NaN,NaN,NaN,NaN,NaN
39,NaN,Van*,Turkey,"3,755 km2 (1,450 sq mi)",NaN,NaN,3 (146 cu mi),NaN,NaN
40,NaN,Peipus,Estonia Russia,"3,555 km2 (1,373 sq mi)",NaN,NaN,3 (6.0 cu mi),NaN,NaN
41,NaN,Uvs*,Mongolia,"3,350 km2 (1,290 sq mi)",NaN,NaN,NaN,NaN,NaN
42,NaN,Poyang,China,"3,210 km2 (1,240 sq mi)",NaN,NaN,3 (6.0 cu mi),NaN,NaN
43,NaN,Tana,Ethiopia,"3,200 km2 (1,200 sq mi)",NaN,NaN,NaN,NaN,NaN
44,NaN,Amadjuak,Canada,"3,115 km2 (1,203 sq mi)",NaN,NaN,NaN,NaN,NaN
45,NaN,Melville,Canada,"3,069 km2 (1,185 sq mi)",NaN,NaN,NaN,NaN,NaN
46,NaN,Bangweulu,Zambia,"3,000 km2 (1,200 sq mi)",NaN,NaN,NaN,NaN,NaN
47,NaN,Dongting,China,"2,820 km2 (1,090 sq mi)",NaN,NaN,NaN,NaN,NaN
48,NaN,Khövsgöl,Mongolia,"2,760 km2 (1,070 sq mi)",NaN,NaN,3 (115.3 cu mi),NaN,NaN
49,NaN,Tonlé Sap,Cambodia,"2,700 km2 (1,000 sq mi)",NaN,NaN,3 (19 cu mi),NaN,NaN
50,NaN,Kivu,Rwanda Democratic Republic of the Congo,"2,700 km2 (1,000 sq mi)",NaN,NaN,3 (120 cu mi),NaN,NaN
51,NaN,Wollaston,Canada,"2,681 km2 (1,035 sq mi)",NaN,NaN,3 (9.5 cu mi),NaN,NaN
52,NaN,Alakol*,Kazakhstan,"2,650 km2 (1,020 sq mi)",NaN,NaN,3 (14.1 cu mi),NaN,NaN
53,NaN,Iliamna,United States,"2,622 km2 (1,012 sq mi)",NaN,NaN,3 (28 cu mi),NaN,NaN
54,NaN,Hulun,China,"2,339 km2 (903 sq mi)",NaN,NaN,3 (28 cu mi),NaN,NaN
55,NaN,Mistassini,Canada,"2,335 km2 (902 sq mi)",NaN,NaN,3 (36 cu mi),NaN,NaN
56,NaN,Edward,Democratic Republic of the Congo Uganda,"2,325 km2 (898 sq mi)",NaN,NaN,3 (9.5 cu mi),NaN,NaN
57,NaN,Mai-Ndombe,Democratic Republic of the Congo,"2,300 km2 (890 sq mi)",NaN,NaN,NaN,NaN,NaN
58,NaN,Nueltin,Canada,"2,279 km2 (880 sq mi)",NaN,NaN,NaN,NaN,NaN
59,NaN,Tai,China,"2,250 km2 (870 sq mi)",NaN,NaN,NaN,NaN,NaN
60,NaN,Southern Indian Lake,Canada,"2,247 km2 (868 sq mi)",NaN,NaN,3 (5.6 cu mi),NaN,NaN
61,NaN,Chany,Russia,"2,000 km2 (770 sq mi)",NaN,NaN,NaN,NaN,NaN

In [80]:
lakes.columns[0]

'Unnamed: 0'

In [81]:
lakes.drop('Unnamed: 0', axis='columns', inplace=True)

In [82]:
lakes

,Name,Countries with shoreline,Area,Length,Maximum depth,Water volume,Thumbnail (same scale for all lakes),Notes
0,Caspian Sea*,Kazakhstan Russia Turkmenistan Azerbaijan Iran,"2 (143,000 sq mi)",NaN,NaN,"3 (18,800 cu mi)",NaN,"Despite its name, the Caspian Sea is often reg..."
1,Superior[n 1],Canada United States,"2 (31,700 sq mi)[14]",[14],[14],"3 (2,900 cu mi)[14]",NaN,"Largest of the Great Lakes by volume, having m..."
2,Victoria,Uganda Kenya Tanzania,"2 (26,590 sq mi)",NaN,NaN,3 (660 cu mi),NaN,The largest lake by area in Africa.[17]
3,Huron[n 1],Canada United States,"2 (23,000 sq mi)[14]",[14],[14],3 (850 cu mi)[14],NaN,"Contains Manitoulin Island, the world's larges..."
4,Michigan[n 1],United States,"2 (22,000 sq mi)[14]",[14],[14],"3 (1,200 cu mi)[14]",NaN,Largest lake contained within one country.
5,Tanganyika,Burundi Tanzania Zambia Democratic Republic of...,"2 (12,600 sq mi)",NaN,NaN,"3 (4,500 cu mi)",NaN,Longest freshwater lake in the world and secon...
6,Baikal,Russia,"2 (12,200 sq mi)",NaN,NaN,"3 (5,700 cu mi)",NaN,Deepest lake in the world and largest volume f...
7,Great Bear Lake,Canada,"2 (12,000 sq mi)",NaN,NaN,3 (536 cu mi),NaN,Largest lake entirely within Canada[21]
8,Malawi,Malawi Mozambique Tanzania,"2 (11,400 sq mi)",NaN,NaN,"3 (2,000 cu mi)",NaN,NaN
9,Great Slave Lake,Canada,"2 (10,000 sq mi)",NaN,NaN,3 (370 cu mi),NaN,Deepest lake in North America[22]
10,Erie,Canada United States,"2 (9,900 sq mi)[14]",[14],[14],3 (117 cu mi)[14],NaN,NaN
11,Winnipeg,Canada,"2 (9,465 sq mi)",NaN,NaN,3 (68 cu mi),NaN,NaN
12,Ontario,Canada United States,"2 (7,320 sq mi)[14]",[14],[14],3 (393 cu mi)[14],NaN,NaN
13,Ladoga,Russia,"2 (7,000 sq mi)",NaN,NaN,3 (218 cu mi),NaN,Largest lake in Europe[23]
14,Balkhash*,Kazakhstan,"2 (6,300 sq mi)",NaN,NaN,3 (25 cu mi),NaN,NaN
15,Vostok,Antarctica,"2 (4,800 sq mi)",NaN,NaN,"3 (1,300 ± 380 cu mi)",NaN,Largest lake in Antarctica
16,Onega,Russia,"2 (3,700 sq mi)",NaN,NaN,3 (68 cu mi),NaN,NaN
17,Titicaca,Bolivia Peru,"2 (3,232 sq mi)",NaN,NaN,3 (214 cu mi),NaN,Largest lake in South America. Has a smaller s...
18,Nicaragua,Nicaragua,"2 (3,191 sq mi)",NaN,NaN,3 (26 cu mi),NaN,Largest lake in Central America
19,Athabasca,Canada,"2 (3,030 sq mi)",NaN,NaN,3 (49 cu mi),NaN,NaN
20,Taymyr,Russia,"2 (2,700 sq mi)",NaN,NaN,3 (3.1 cu mi),NaN,Largest lake entirely north of the Arctic Circ...
21,Turkana*,Ethiopia Kenya,"2 (2,473 sq mi)",NaN,NaN,3 (49 cu mi),NaN,Largest permanent desert lake and the world's ...
22,Reindeer Lake,Canada,"2 (2,440 sq mi)",NaN,NaN,3 (22.85 cu mi),NaN,NaN
23,Issyk-Kul*,Kyrgyzstan,"2 (2,400 sq mi)",NaN,NaN,3 (417 cu mi),NaN,NaN
24,Urmia*,Iran,"2 (2,317 sq mi)",NaN,NaN,NaN,NaN,NaN
25,Vänern,Sweden,"2 (2,141 sq mi)",NaN,NaN,3 (37 cu mi),NaN,Largest lake in the European Union
26,Winnipegosis,Canada,"2 (2,086 sq mi)",NaN,NaN,NaN,NaN,NaN
27,Albert,Uganda Democratic Republic of the Congo,"2 (2,046 sq mi)",NaN,NaN,3 (67 cu mi),NaN,NaN
28,Mweru,Zambia Democratic Republic of the Congo,"2 (1,980 sq mi)",NaN,NaN,3 (9.1 cu mi),NaN,NaN
29,Nettilling,Canada,"2 (1,956 sq mi)",NaN,NaN,NaN,NaN,Lake is on Baffin Island and is the largest la...
...,...,...,...,...,...,...,...,...
32,Great Salt Lake*,United States,"2 (1,800 sq mi)",NaN,NaN,3 (4.54 cu mi),NaN,Largest saltwater lake in the Western Hemisphe...
33,Qinghai Lake*,China,"2 (1,733 sq mi) (2007)",NaN,NaN,NaN,NaN,NaN
34,Saimaa,Finland,"≈ 4,400 km2 (1,700 sq mi)",NaN,NaN,3 (8.6 cu mi),NaN,NaN
35,Lake of the Woods,Canada United States,"4,350 km2 (1,680 sq mi)",NaN,NaN,3 (4.7 cu mi),NaN,"Most islands of any lake, with around 14,632 i..."
36,Khanka,China Russia,"4,190 km2 (1,620 sq mi)",NaN,NaN,3 (4.4 cu mi),NaN,NaN
37,Sarygamysh,Uzbekistan Turkmenistan,"3,955 km2 (1,527 sq mi)",NaN,NaN,3 (16.45 cu mi),NaN,NaN
38,Dubawnt,Canada,"3,833 km2 (1,480 sq mi)",NaN,NaN,NaN,NaN,NaN
39,Van*,Turkey,"3,755 km2 (1,450 sq mi)",NaN,NaN,3 (146 cu mi),NaN,NaN
40,Peipus,Estonia Russia,"3,555 km2 (1,373 sq mi)",NaN,NaN,3 (6.0 cu mi),NaN,NaN
41,Uvs*,Mongolia,"3,350 km2 (1,290 sq mi)",NaN,NaN,NaN,NaN,NaN
42,Poyang,China,"3,210 km2 (1,240 sq mi)",NaN,NaN,3 (6.0 cu mi),NaN,NaN
43,Tana,Ethiopia,"3,200 km2 (1,200 sq mi)",NaN,NaN,NaN,NaN,NaN
44,Amadjuak,Canada,"3,115 km2 (1,203 sq mi)",NaN,NaN,NaN,NaN,NaN
45,Melville,Canada,"3,069 km2 (1,185 sq mi)",NaN,NaN,NaN,NaN,NaN
46,Bangweulu,Zambia,"3,000 km2 (1,200 sq mi)",NaN,NaN,NaN,NaN,NaN
47,Dongting,China,"2,820 km2 (1,090 sq mi)",NaN,NaN,NaN,NaN,NaN
48,Khövsgöl,Mongolia,"2,760 km2 (1,070 sq mi)",NaN,NaN,3 (115.3 cu mi),NaN,NaN
49,Tonlé Sap,Cambodia,"2,700 km2 (1,000 sq mi)",NaN,NaN,3 (19 cu mi),NaN,NaN
50,Kivu,Rwanda Democratic Republic of the Congo,"2,700 km2 (1,000 sq mi)",NaN,NaN,3 (120 cu mi),NaN,NaN
51,Wollaston,Canada,"2,681 km2 (1,035 sq mi)",NaN,NaN,3 (9.5 cu mi),NaN,NaN
52,Alakol*,Kazakhstan,"2,650 km2 (1,020 sq mi)",NaN,NaN,3 (14.1 cu mi),NaN,NaN
53,Iliamna,United States,"2,622 km2 (1,012 sq mi)",NaN,NaN,3 (28 cu mi),NaN,NaN
54,Hulun,China,"2,339 km2 (903 sq mi)",NaN,NaN,3 (28 cu mi),NaN,NaN
55,Mistassini,Canada,"2,335 km2 (902 sq mi)",NaN,NaN,3 (36 cu mi),NaN,NaN
56,Edward,Democratic Republic of the Congo Uganda,"2,325 km2 (898 sq mi)",NaN,NaN,3 (9.5 cu mi),NaN,NaN
57,Mai-Ndombe,Democratic Republic of the Congo,"2,300 km2 (890 sq mi)",NaN,NaN,NaN,NaN,NaN
58,Nueltin,Canada,"2,279 km2 (880 sq mi)",NaN,NaN,NaN,NaN,NaN
59,Tai,China,"2,250 km2 (870 sq mi)",NaN,NaN,NaN,NaN,NaN
60,Southern Indian Lake,Canada,"2,247 km2 (868 sq mi)",NaN,NaN,3 (5.6 cu mi),NaN,NaN
61,Chany,Russia,"2,000 km2 (770 sq mi)",NaN,NaN,NaN,NaN,NaN

In [58]:
lakes['Countries with shoreline'][0]

'Kazakhstan\xa0Russia\xa0Turkmenistan\xa0Azerbaijan\xa0Iran'

In [92]:
lakes.replace(to_replace = r'\xa0', value= r' ', regex=True, inplace=True)

In [93]:
lakes['Countries with shoreline'][0]

'Kazakhstan Russia Turkmenistan Azerbaijan Iran'

In [94]:
lakes['Area'][0]

'2 (143,000 sq mi)'

In [95]:
lakes.Area = lakes.Area.replace(to_replace = r'^.*\((.*) sq mi\).*$', value=r'\1', regex=True)

In [96]:
lakes.Area

0     143,000
1      31,700
2      26,590
3      23,000
4      22,000
5      12,600
6      12,200
7      12,000
8      11,400
9      10,000
10      9,900
11      9,465
12      7,320
13      7,000
14      6,300
15      4,800
16      3,700
17      3,232
18      3,191
19      3,030
20      2,700
21      2,473
22      2,440
23      2,400
24      2,317
25      2,141
26      2,086
27      2,046
28      1,980
29      1,956
       ...
32      1,800
33      1,733
34      1,700
35      1,680
36      1,620
37      1,527
38      1,480
39      1,450
40      1,373
41      1,290
42      1,240
43      1,200
44      1,203
45      1,185
46      1,200
47      1,090
48      1,070
49      1,000
50      1,000
51      1,035
52      1,020
53      1,012
54        903
55        902
56        898
57        890
58        880
59        870
60        868
61        770
Name: Area, Length: 62, dtype: object

In [102]:
lakes.Area.replace(to_replace = r',', value=r'', regex=True)

0     143000
1      31700
2      26590
3      23000
4      22000
5      12600
6      12200
7      12000
8      11400
9      10000
10      9900
11      9465
12      7320
13      7000
14      6300
15      4800
16      3700
17      3232
18      3191
19      3030
20      2700
21      2473
22      2440
23      2400
24      2317
25      2141
26      2086
27      2046
28      1980
29      1956
       ...
32      1800
33      1733
34      1700
35      1680
36      1620
37      1527
38      1480
39      1450
40      1373
41      1290
42      1240
43      1200
44      1203
45      1185
46      1200
47      1090
48      1070
49      1000
50      1000
51      1035
52      1020
53      1012
54       903
55       902
56       898
57       890
58       880
59       870
60       868
61       770
Name: Area, Length: 62, dtype: object